<a href="https://colab.research.google.com/github/ivywanjage/cdav/blob/main/numpy2tuesday.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
morse_code = {
    'A': '.-',    'B': '-...',  'C': '-.-.',  'D': '-..',   'E': '.',
    'F': '..-.',  'G': '--.',   'H': '....',  'I': '..',    'J': '.---',
    'K': '-.-',   'L': '.-..',  'M': '--',    'N': '-.',    'O': '---',
    'P': '.--.',  'Q': '--.-',  'R': '.-.',   'S': '...',   'T': '-',
    'U': '..-',   'V': '...-',  'W': '.--',   'X': '-..-',  'Y': '-.--',
    'Z': '--..',  '0': '-----', '1': '.----', '2': '..---', '3': '...--',
    '4': '....-', '5': '.....', '6': '-....', '7': '--...', '8': '---..',
    '9': '----.'
}
message = input("Enter a message: ").upper()
result = ""
i = 0
while i < len(message):
    letter = message[i]
    if letter in morse_code:
        result = result + morse_code[letter] + " "
    i = i + 1
print(result)


Enter a message: hello world
.... . .-.. .-.. --- .-- --- .-. .-.. -.. 


In [ ]:
morse_dictionary={'A':'.-', 'B':'-...','C':'-.-.','D':'-..','E':'.','F':'..-.',
                  'G':'--.','H':'....','I':'..','J':'.---','K':'-.-','L':'.-..',
                  'M':'--','N':'-.','O':'---','P':'.--.','Q':'--.-','R':'.-.',
                  'S':'...','T':'-','U':'..-','V':'...-','W':'.--','X':'-..-',
                  'Y':'-.--','Z':'--..','1':'.----','2':'..---','3':'...--',
                  '4':'....-','5':'.....','6':'-....','7':'--...','8':'---..',
                  '9':'----.','0':'-----'
                  }
user_input=input("Enter message to be encoded ")
result=""
for character in user_input.upper():
  if character in morse_dictionary:
    result+=morse_dictionary[character]+" "
print("Morse code:",result)

Enter message to be encoded hello world
Morse code: .... . .-.. .-.. --- .-- --- .-. .-.. -.. 


In [ ]:
scores=[78,82,80,45]

In [ ]:
added_scores=[]
for score in scores:
  added_scores.append(score+5)
  print(added_scores)

[83]
[83, 87]
[83, 87, 85]
[83, 87, 85, 50]


In [ ]:
import numpy as np
scores=np.array(scores)
scores+5

array([83, 87, 85, 50])

vectorization=improvement over the loops


used for a huge dataset

In [ ]:
end_term_scores=[30,45,27,34]
cat_scores=[23,21,18,26]
assignment_scores=[9,6,2,8]
end_term_scores+cat_scores+assignment_scores

[30, 45, 27, 34, 23, 21, 18, 26, 9, 6, 2, 8]

In [ ]:
np.sqrt(scores)#square root
np.exp(scores)#exponential
np.log(scores)#natural logarithm
np.abs(scores)#absolute values

array([78, 82, 80, 45])

In [ ]:
np.random.seed(42)
np.random.randint(40,100,50)

array([78, 91, 68, 54, 82, 47, 60, 78, 97, 58, 62, 50, 50, 63, 92, 75, 79,
       63, 42, 61, 92, 41, 63, 83, 69, 77, 41, 99, 60, 72, 51, 97, 61, 83,
       64, 88, 66, 98, 81, 67, 99, 55, 54, 86, 90, 83, 94, 91, 96, 42])

In [ ]:
array=np.array([78, 91, 68, 54, 82, 47, 60, 78, 97, 58, 62, 50, 50, 63, 92, 75, 79,
       63, 42, 61, 92, 41, 63, 83, 69, 77, 41, 99, 60, 72, 51, 97, 61, 83,
       64, 88, 66, 98, 81, 67, 99, 55, 54, 86, 90, 83, 94, 91, 96, 42])
array+5

array([ 83,  96,  73,  59,  87,  52,  65,  83, 102,  63,  67,  55,  55,
        68,  97,  80,  84,  68,  47,  66,  97,  46,  68,  88,  74,  82,
        46, 104,  65,  77,  56, 102,  66,  88,  69,  93,  71, 103,  86,
        72, 104,  60,  59,  91,  95,  88,  99,  96, 101,  47])

In [ ]:
np.mean(array)

np.float64(71.86)

In [ ]:
array_2=np.array([ 83,  96,  73,  59,  87,  52,  65,  83, 102,  63,  67,  55,  55,
        68,  97,  80,  84,  68,  47,  66,  97,  46,  68,  88,  74,  82,
        46, 104,  65,  77,  56, 102,  66,  88,  69,  93,  71, 103,  86,
        72, 104,  60,  59,  91,  95,  88,  99,  96, 101,  47])
np.mean(array_2)


np.float64(76.86)

In [ ]:
class_scores=np.random.randint(40,101,50)
bonus_class_scores=class_scores+5
print("the mean of",class_scores,"is",np.mean(class_scores))
print("the mean of",bonus_class_scores,"is",np.mean(bonus_class_scores))

the mean of [52 71 46 98 90 61 67 41 81 84 96 92 45 67 67 83 83 59 69 50 97 94 67 64
 78 72 40 96 66 96 91 52 80 42 78 45 47 66 48 76 72 90 81 83 63 54 98 93
 71 71] is 71.46
the mean of [ 57  76  51 103  95  66  72  46  86  89 101  97  50  72  72  88  88  64
  74  55 102  99  72  69  83  77  45 101  71 101  96  57  85  47  83  50
  52  71  53  81  77  95  86  88  68  59 103  98  76  76] is 76.46


In [ ]:
class_scores[class_scores<=95]

array([52, 71, 46, 90, 61, 67, 41, 81, 84, 92, 45, 67, 67, 83, 83, 59, 69,
       50, 94, 67, 64, 78, 72, 40, 66, 91, 52, 80, 42, 78, 45, 47, 66, 48,
       76, 72, 90, 81, 83, 63, 54, 93, 71, 71])

In [ ]:
class_scores[~class_scores<=95]

array([52, 71, 46, 98, 90, 61, 67, 41, 81, 84, 96, 92, 45, 67, 67, 83, 83,
       59, 69, 50, 97, 94, 67, 64, 78, 72, 40, 96, 66, 96, 91, 52, 80, 42,
       78, 45, 47, 66, 48, 76, 72, 90, 81, 83, 63, 54, 98, 93, 71, 71])

In [ ]:
import numpy as np
scores=np.array([98,70,56,97,46])
scores[~(scores>=95) &(scores>60) | (scores<50)]

array([70, 46])

In [ ]:
np.random.seed(42)
marks=np.random.randint(40,101,50)
print(marks)

[ 78  91  68  54  82  47 100  60  78  97  58  62  50  50  63  92  75  79
  63  42  61  92  41  63  83  69  77  41  99  60  72  51  97  61 100  83
  64  88  66  98  81  67  99  55  54  86  90  83  94  91]


In [ ]:
import numpy as np
marks[~(marks>=50)]

array([47, 42, 41, 41])

In [ ]:

lolol=marks[~(marks>=50)]
lolol.size

4

In [ ]:
marks[(marks>80)]

array([ 91,  82, 100,  97,  92,  92,  83,  99,  97, 100,  83,  88,  98,
        81,  99,  86,  90,  83,  94,  91])

In [ ]:
pinpin=marks[(marks>80)]
pinpin.size

20

In [ ]:
import numpy as np
scores=np.array([98,70,56,97,46])
scores[~(scores>=95) &(scores>60) | (scores<50)]

array([70, 46])

In [ ]:
~(scores<=95)

array([ True, False, False,  True, False])

In [ ]:
np.where(scores<50,"Fail","Pass")

array(['Pass', 'Pass', 'Pass', 'Pass', 'Fail'], dtype='<U4')

np.vectorize and np.frompyfunc-allow you to convert a normal function into a vector function

In [ ]:
def strtoupper(word):
  return word.upper()

In [ ]:
names=np.array(["John","Mary","Edward"])
for name in names:
 print(strtoupper(name))

JOHN
MARY
EDWARD


In [ ]:
np.vectorize(strtoupper)(names)

array(['JOHN', 'MARY', 'EDWARD'], dtype='<U6')

In [ ]:
vectoupper=np.frompyfunc(strtoupper,1,1)#number of argument it takes,number of values it returns
vectoupper(names)

array(['JOHN', 'MARY', 'EDWARD'], dtype=object)

In [ ]:
def adder(num):
  return num+5
adder(90)

95

In [ ]:
uadder=np.vectorize(adder)

In [ ]:
score=np.array([90,45,67])
uadder(score)

array([95, 50, 72])

In [ ]:
uadder2=np.frompyfunc(adder,1,1)
uadder2(score)

array([95, 50, 72], dtype=object)

In [ ]:
def add_two(num1,num2):
  return num1+num2

In [ ]:
arr_1=np.array([1,2,3])
arr_2=np.array([3,4,5])
uadd_two=np.vectorize(add_two)
uadd_two(arr_1,arr_2)

array([4, 6, 8])

In [ ]:
def stat(num1,num2):
  return (num1+num2,(num1+num2)/2)


In [ ]:
ustat=np.frompyfunc(stat,2,2)
arr_1=np.array([1,2,3])
arr_2=np.array([3,4,5])
ustat(arr_1,arr_2)

(array([4, 6, 8], dtype=object), array([2.0, 3.0, 4.0], dtype=object))

In [ ]:
sum_of_arrs,mean_of_arrs=ustat(arr_1,arr_2)

In [ ]:
sum_of_arrs

array([4, 6, 8], dtype=object)

In [ ]:
mean_of_arrs

array([2.0, 3.0, 4.0], dtype=object)

create a function called summary,that does the mean,median,std dev,var,dtype,size,shape and grades of students...

In [ ]:
import numpy as np


def assign_grade(score):
    """Helper function to map numerical scores to letter grades."""
    if score >= 80:
        return "A"
    elif score >= 70:
        return "B"
    elif score >= 60:
        return "C"
    elif score >= 50:
        return "D"
    else:
        return "F"


# Vectorize the grading function so it can operate on NumPy arrays
get_grades = np.vectorize(assign_grade)


def summary(arr):
    """Calculates summary statistics and grades for an array of student marks."""
    # Convert input to a NumPy array if it isn't one already
    arr = np.asarray(arr)

    stats = {
        "mean": np.mean(arr),
        "median": np.median(arr),
        "std_dev": np.std(arr),
        "variance": np.var(arr),
        "dtype": arr.dtype,
        "size": arr.size,
        "shape": arr.shape,
        "grades": get_grades(arr),
    }

    return stats

# afternoon lesson

In [ ]:
import numpy as np

marks = np.array([
[78, 81, 74, 90],
[65, 72, 80, 76],
[92, 88, 95, 91],
[55, 60, 58, 63],
[84, 79, 86, 88]
])
marks[0]

array([78, 81, 74, 90])

In [ ]:
marks[0,0]

np.int64(78)

In [ ]:
marks[0][-1]

np.int64(90)

In [ ]:
marks.shape
#number of rows,columns

(5, 4)

In [ ]:
marks.ndim
#number of axes

2

In [ ]:
marks.size

20

axis

0=rows and 1=columns

In [ ]:
marks[-1,-1]#last student

np.int64(88)

In [ ]:
marks[:,:2]#all rows,all columns index 0 and 1

array([[78, 81],
       [65, 72],
       [92, 88],
       [55, 60],
       [84, 79]])

In [ ]:
marks[:,1]

array([81, 72, 88, 60, 79])

In [ ]:
marks[:3]

array([[78, 81, 74, 90],
       [65, 72, 80, 76],
       [92, 88, 95, 91]])

In [ ]:
marks[:,0:2]

array([[78, 81],
       [65, 72],
       [92, 88],
       [55, 60],
       [84, 79]])

In [ ]:
marks[1:4,1:3]

array([[72, 80],
       [88, 95],
       [60, 58]])