<a href="https://colab.research.google.com/github/ivywanjage/cdav/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import numpy as np
np.__version__

'2.0.2'

nd.array-n dimensions array/primary data structure in numpy


n represents any number up to infinity


nd array-collection of homogenous items,stored in a continuous section of memory and allows implementation of vectorization

syntax of an np array is usually:
variable name=np.array([])


In [5]:
#creating an array
age=np.array([10])#this is a zero dimension array created from a scalar value
print(age)

[10]


In [4]:
#1 dimension array-array created from a flat list
ages=np.array([10,12,11,15])
print(ages)

[10 12 11 15]


when printing an array there are no commas

In [6]:
#2 dimension list because it has two continuos opening brackets
yob_age=np.array([[2000,26],[2002,24]])
print(yob_age)

[[2000   26]
 [2002   24]]


In [13]:
#3 dimension
cube_data=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(cube_data)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [10]:
marks=np.array([74,81,92,65,78])
print(marks)

[74 81 92 65 78]


ndim-number of dimensions

In [11]:
marks.ndim

1

In [14]:
cube_data.ndim

3

.shape

In [15]:
marks.shape

(5,)

In [16]:
yob_age.shape

(2, 2)

In [17]:
cube_data.shape

(2, 3, 3)

.size-total number of elements

In [18]:
marks.size

5

In [19]:
yob_age.size

4

In [20]:
cube_data.size

18

.dtype

In [21]:
marks.dtype

dtype('int64')

In [23]:
names=np.array(["John","Jane","Alfred"])

In [24]:
names.dtype

dtype('<U6')

In [53]:
def lololol(number):
  number=np.array([10,20,30,40])
  print(number.ndim)
  print(number.shape)
  print(number.size)
  print(number.dtype)
lololol(number)

1
(4,)
4
int64


In [59]:
def lololol(number):

  print(number.ndim)
  print(number.shape)
  print(number.size)
  print(number.dtype)
lololol(number)
if number==type in list:
  print()
else:
  print()

1
(4,)
4
int64


In [56]:
marks=[1,2,3]
type(marks)

list

In [ ]:
def describer(item):
  if type(item)==np.ndarray:
    return(item.size,item.shape,item.dtype,item.ndim)
  else:
    lshape=()
    ldtype=""
    lndim=1
    dim_1=len(item)
    dim_2=0
    for i in item:
      if type(i)==list:
        dim_2=len(i)
        for x in i:
          if dtype=="":
            ldtype=type(x)
          elif ldtype !=type(x):
            print(type(x))
            ldtype="mixed types"
          else:
            if ldtype=="":
              ldtype=type(i)
            elif

# numpy slicing

In [65]:
import numpy as np
a=np.arange(20)
print("a[15]=",a[15])
print("a[10]=",a[-8:17:1])
print("a[10:]=",a[10:])

a[15]= 15
a[10]= [12 13 14 15 16]
a[10:]= [10 11 12 13 14 15 16 17 18 19]


In [77]:
scores = np.array([82,75,91,68,80])
scores[1:4]
print(scores)
#im wrong here

[82 75 91 68 80]


In [79]:
np.arange(0,20,2)
#specifies step value of two to generate even integers,specifies step size

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [78]:
np.linspace(0,100,5)
#specifies exact total count of numbers including endpoint

array([  0.,  25.,  50.,  75., 100.])

In [85]:
#generating random data
np.random.randint(0,100,10)

array([20, 82, 86, 74, 74, 87, 99, 23,  2, 21])

In [84]:
#every time you run the code you get the same numbers
np.random.seed(42)
np.random.randint(0,100,5)

array([51, 92, 14, 71, 60])

In [101]:
np.random.seed(42)
np.random.randint(0,100,40)


array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74, 87, 99, 23,  2, 21, 52,  1,
       87, 29, 37,  1, 63, 59, 20, 32, 75, 57, 21, 88, 48, 90, 58, 41, 91,
       59, 79, 14, 61, 61, 46])

In [104]:
np.random.seed(42)
scores=np.random.randint(0,100,40)
print("first five scores are",scores[:5])
print("last five scores are",scores[-5:])

first five scores are [51 92 14 71 60]
last five scores are [79 14 61 61 46]
